# Multi-stage build producing a slim runtime image from Next's standalone
# output. Requires `output: 'standalone'` in next.config.ts.

FROM node:22.17.0-alpine AS base

# ---- dependencies -----------------------------------------------------------
FROM base AS deps
# https://github.com/nodejs/docker-node#nodealpine — sharp and other native deps
RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY package.json package-lock.json .npmrc ./
RUN npm ci

# ---- migrator ---------------------------------------------------------------
# Run this against the production database before the app starts. The runtime
# image below is a traced standalone bundle and has no Payload CLI.
FROM base AS migrator
RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
ENV NODE_ENV=production
CMD ["npx", "payload", "migrate"]

# ---- build ------------------------------------------------------------------
FROM base AS builder
RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# The build touches no database: every route under (frontend) renders on demand
# (see the force-dynamic in its layout), so nothing is prerendered and nothing
# is queried here. DATABASE_URL is still declared because payload.config reads
# it at import, but it is never connected to and needs no real value.
ARG DATABASE_URL=postgresql://build:build@127.0.0.1:5432/build
# Build-time only. The real secret is supplied to the container at runtime.
ARG PAYLOAD_SECRET=build-time-placeholder
ARG NEXT_PUBLIC_SERVER_URL
# NEXT_PUBLIC_* is inlined into the client bundle here, at build time. Setting
# it on the container later only reaches server-side code — the browser gets
# whatever was frozen in now. It also ends up readable in the published image,
# so never pass a real secret this way.

ENV DATABASE_URL=$DATABASE_URL \
    PAYLOAD_SECRET=$PAYLOAD_SECRET \
    NEXT_PUBLIC_SERVER_URL=$NEXT_PUBLIC_SERVER_URL \
    NEXT_TELEMETRY_DISABLED=1 \
    NODE_ENV=production

# No `payload migrate` here. Migrations run at deploy time from the migrator
# image, gated before the app starts (see docker-compose.yml). Running them
# from a build would migrate the target database on every image build,
# including builds that then fail, and before the new code is live.
RUN npm run build

# ---- runtime ----------------------------------------------------------------
FROM base AS runner
RUN apk add --no-cache libc6-compat
WORKDIR /app

ENV NODE_ENV=production \
    NEXT_TELEMETRY_DISABLED=1 \
    PORT=3000 \
    HOSTNAME=0.0.0.0

RUN addgroup --system --gid 1001 nodejs \
 && adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

# Payload writes uploads here (see Media.upload.staticDir). Mount a volume on
# this path or uploads are lost when the container is replaced — which is what
# happened to the media already on cms.prodeprod.com.
RUN mkdir -p /app/public/media && chown -R nextjs:nodejs /app/public/media

USER nextjs
EXPOSE 3000

# server.js is generated by next build's standalone output
CMD ["node", "server.js"]
